#!/bin/bash

printf "PHPStan started..."

filesToCheck=$(git diff --name-only --diff-filter=d HEAD src)
output=$(php vendor/bin/phpstan analyse $filesToCheck --error-format=raw --level 7)
if [ -z "$output" ]
then
    printf "\nGood job!\n"
    exit 0
else
    printf "$output\n"
    printf "\nCommit aborted, fix your code!\n"
    exit 1
fi
